# Generated by Django 4.0.6 on 2022-08-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='avatar_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='chats',
            field=models.ManyToManyField(blank=True, null=True, to='api.chatmodel'),
        ),
    ]
